# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-08 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='password',
            field=models.CharField(default='secret', max_length=100),
            preserve_default=False,
        ),
    ]
